### ISSUE TITLE
Migrate to asp.net core 2.0

### ISSUE THREAD

**Issue by tbolon** [microsoftgraph/aspnetcore-connect-sample#1]
Hi,

There was significant changes in the [asp.net core 2.0 authentication](https://github.com/aspnet/Announcements/issues/262) components.

Do you plan to update this sample to this new version ?

**Comment by jamescro** [comment]
The work to do this isn't currently scheduled, but it is something that we will do when we have the appropriate resources.

**Comment by alvipeo** [comment]
hey guys! can you update this sample to ASP.NET Core 2.0???? WE REALLY NEED It. Thank you!

**Comment by mark-szabo** [comment]
Hi @alvipeo I'll work on this in the next few weeks. There was some compatibility issue with netcore1.1 and MSAL, but now we can try to solve that too with netcore2.0. :)

**Comment by mark-szabo** [comment]
Hi everybody, sample updated to ASP.NET Core 2.0. If you find a bug or have some suggestions, please keep us informed! :)
Have a nice weekend!

**Comment by jamescro** [comment]
Thanks!
