### ISSUE TITLE
User.Identity.Name

### ISSUE THREAD

**Issue by KaiserSozei87** [microsoftgraph/aspnetcore-connect-sample#15]
Any idea why User.Identity.Name would be null? I was previously using Azure AD only authentication out of the box from Microsoft. I have no switched over to using this sample with the Graph API and the /common/v2.0 library. Feel like i've missed something somewhere but not sure where to start?

**Comment by mark-szabo** [comment]
Thanks, fixed.

More info: https://cerkit.com/2017/07/25/asp-net-core-jwt-tokens-and-user-identity-name-property/

**Comment by KaiserSozei87** [comment]
Nice fix. Thanks
