### ISSUE TITLE
Client that uses custom API and Graph

### ISSUE THREAD

**Issue by hernan-almeida** [microsoftgraph/aspnetcore-connect-sample#16]
For a client (web) application that needs to make requests to Graph and another API (e.g. myapi.azurewebsites.net), what is the best practice?

Should a client acquire two separate access tokens? One with the Graph audience and one for myapi.azurewebsites.net? Or, is there a way to generate a token with an audience of myapi.azurewebsites.net that has scopes for Graph?

**Comment by mark-szabo** [comment]
Hi @hernan-almeida 
First question: is the API hosted on myapi.azurewebsites.net written by you? I would think of using the auth token used by Graph to authenticate with the API using Azure AD.

**Comment by hernan-almeida** [comment]
Hey @mark-szabo it is, but the token that comes back from Graph has an audience for graph.microsoft.com. Since my API is not open to everyone, wouldn't trusting graph.microsoft.com make it so that anyone with that scope can authenticate to my API? I believe the OAUTH2 spec has support for multi audience "aud" field but I cant seem to figure out if this is supported in AAD and Graph.

Since the audience property is supposed to be set to what the token is intended for, it seems that I either need a token with two audiences, or, I'm stuck using two different access tokens.

**Comment by mark-szabo** [comment]
thanks for the info! To be honest I'm not a pro on the token side, so I'll ask one of my peers in the Microsoft Graph team. @jasonjoh can you please have a look on this question? :)

**Comment by mark-szabo** [comment]
@hernan-almeida by a coincidence, I'm working on a frontend webapp right now where I'm calling an ASP.NET Core Web API. Have a look on this tutorial, I think that will help!
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2

**Comment by hernan-almeida** [comment]
@mark-szabo that is what I'm doing now to call my API but the questions still remains... what if your frontend is calling both a .Net Core API and also Graph. Can a single jwt be used to authenticate to both services?

**Comment by mark-szabo** [comment]
Yes, in theory yes. You are validating the token you got back from AD. Keep in mind there is an `id_token` (used to authenticate to AD and your API) and an `authorization_code` (for Microsoft Graph).

**Comment by hernan-almeida** [comment]
"In theory yes" - as long as Graph can validate a jwt with multi audience field. The web app gets an `id_token` from AD when the user is authenticated but I do not authenticate to the API with the `id_token`. The API works similar to Graph in that it also looks for an `authorization_code` with the proper audience and scope/s.

Currently I have to take my `id_token` from the auth flow and turn that into two separate `authorization_code`s (one for graph with `aud: http://graph.microsoft.com` and one with `aud: http://myapi.com`).

**Comment by mark-szabo** [comment]
Yeah, if you are using an `authorization_code` to access your api, you cannot use the same as you are using for Graph as `authorization_code`s are url specific and not registered app specific. In the app I'm working on right now, I'm using the `id_token` to access my API, so that's what I was thinking about. 

Although you are basically using the same `id_token` for both (but exchange it separately for two `authorization_code`s before calling the APIs).

There's a great tool called https://jwt.ms/ where you can decode your JWT tokens and see what they contain.

**Comment by mark-szabo** [comment]
@hernan-almeida were your question answered and can I close the issue, or can I help you furthermore somehow?
