### ISSUE TITLE
Has this been outdated by "AddMicrosoftAccount" in the auth pipeline?

### ISSUE THREAD

**Issue by Sharor** [microsoftgraph/aspnetcore-connect-sample#19]
I came upon this https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.1&tabs=aspnetcore2x 

According to the docs it allows you to sign in with either work, personal or school microsoft account 🙂 

I assume the "AzureAD" and custom Auth builder can be setup through this in a more general way or is there something I'm missing? 😉

**Comment by mark-szabo** [comment]
As far as I see this works with personal Microsoft Accounts only and not with work or school accounts. After a short scan, my understanding is that this library was created to have an easy way to integrate Microsoft account login when using other social identity providers (Facebook, Google). So if you are using AzureAD login and no other identity provider, I'd stick with the normal MSAL implementation seen in this sample.

**Comment by Sharor** [comment]
Thank you @mark-szabo, that's what I figured but I could not see through it 😉 

Also your example here has served me very well for a couple of months, good stuff!

**Comment by mark-szabo** [comment]
I'm glad I was able to help! :)
