### ISSUE TITLE
Migrate to Azure AD v2

### ISSUE THREAD

**Issue by tbolon** [microsoftgraph/aspnetcore-connect-sample#2]
This sample still use the Azure AD v1 endpoint. Do you plan to migrate to the new v2.0 endpoint ?

**Comment by jamescro** [comment]
This is something that we would like to do. I believe that Mark ran into some conflicts between the MSAL library (which uses the v2.0 endpoint) and ASP.NET Core dependencies. Is that correct, Mark?

**Comment by mark-szabo** [comment]
Correct. There was conflict in some Odin packages. It could be solved in netcore2.0.

**Comment by mark-szabo** [comment]
Hi everybody, sample updated to implement MSAL (Azure AD v2.0). If you find a bug or have some suggestions, please keep us informed! :)
Have a nice week!
