### ISSUE TITLE
Release version for ADAL (Azure AD v1.0)

### ISSUE THREAD

**Issue by marcoforce** [microsoftgraph/aspnetcore-connect-sample#26]
Are there any plans for the release Version for ADAL or Azure Endpoint v1.0?

I'm trying to play around in this solution but I'm not making any progress.

**Comment by mark-szabo** [comment]
HI @marcoforce 
There is a non-release version of this sample using aspnetcore2.0 and ADAL. You can reach it here: https://github.com/microsoftgraph/aspnetcore-connect-sample/tree/6d2fcf63eefe4b61d769e4ce93050de736e0ab44

Please keep in mind that I don't guarantee that it will build and run without issues.

**Comment by marcoforce** [comment]
May I know which codes or files are needed so that we can Integrate Microsoft Graph API to our existing .Net Core 2.0 API? Our main objective is to get the claims when the user login and so that we can use that particular claims to our conditions for authorization. Example: claims = joblevel, we will use the 'joblevel' to create a condition just like `IF joblevel => 8 user is authorized else error 401`

**Comment by jasonjoh** [comment]
Closing issue as we are archiving this repository.
