### ISSUE TITLE
This should not encourage people to put their ClientSecret on the appsettings.json file

### ISSUE THREAD

**Issue by migueldeicaza** [microsoftgraph/aspnetcore-connect-sample#27]
Instead this should direct users to add the key to their user secrets, like this:

```
dotnet user-secrets set "AzureAd:ClientSecret" "123123123123"
```

**Comment by mark-szabo** [comment]
You are absolutely right, but that would add one extra step to run the sample. For a newbie this can be one more hard step. And as you can see we remind developers all the times to use certificates instead of secrets in production.
