### ISSUE TITLE
Azure AD B2C

### ISSUE THREAD

**Issue by JimBobSquarePants** [microsoftgraph/aspnetcore-connect-sample#29]
Is there an equivalent solution utilizing Azure AD B2C? 

Is it even compatible with Microsoft Graph API?

I'm unable to get tokens generated via my B2C portal to authenticate against the Graph API.

**Comment by mark-szabo** [comment]
Hi @JimBobSquarePants sorry for not getting back to you earlier! Azure AD B2C works with MSAL only, but this sample is using MSAL, so in theory you should be able to use this sample to get it working. What is the issue you are facing? Do you have an exception message for example?

**Comment by mark-szabo** [comment]
Moreover have a look on this [sample](https://github.com/AzureADQuickStarts/B2C-GraphAPI-DotNet) and this [docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet) which are describing the ways to use Microsoft Graph with AzureAD B2C.

**Comment by mark-szabo** [comment]
Please reopen if you're still facing issues getting Microsoft Graph to work with Azure AD B2C!
