### ISSUE TITLE
HttpRequestException: Response status code does not indicate success: 404 (Not Found)

### ISSUE THREAD

**Issue by arshadwhoami** [microsoftgraph/aspnetcore-connect-sample#30]
HI iam trying to use this sample for single tenant app,I have change the authority  also ,but getting this error reponse code doesnot indicate success please help me with this

**Comment by mark-szabo** [comment]
Hi @arshad9160
Can you please elaborate when and where you are getting this error, what does your appsettings contain, and maybe attach a stack trace?

Thank you and Merry Christmas! 🎄

**Comment by arshadwhoami** [comment]
Hi @mark-szabo  I resolved the error  there was some code missing .thank you for reply

**Comment by mark-szabo** [comment]
Thank you @arshad9160 for taking the time to follow up! 😊
Maybe if you could describe what the issue was and what code was missing, you'd be able to help those with the same issue find the solution easier in the future!
