### ISSUE TITLE
sessiontokencache 'TokenCache.HasStateChanged' is obsolete

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/aspnetcore-connect-sample#31]
The sessiontokencache 'TokenCache.HasStateChanged' is obsolete. Please update the sample.
Used in the SessionTokenCache class ofc.

**Comment by mark-szabo** [comment]
With MSAL 3 we aren't using the SessionTokenCache anymore (it is included in MSAL), so I'll close this issue. Thanks for reporting!
