### ISSUE TITLE
Need example for using a certificate to authenticate

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/aspnetcore-connect-sample#32]
I need an example of how to authenticate using a certificate in this project please.

**Comment by mark-szabo** [comment]
Hi @RayGHeld, can you please check this sample? https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential

Let me know whether you were able to implement certificate auth based on these samples!

**Comment by mark-szabo** [comment]
Please reopen the issue if you need more information!
