### ISSUE TITLE
Access denied when trying to get mail messages

### ISSUE THREAD

**Issue by tgallatin** [microsoftgraph/aspnetcore-connect-sample#37]
I'm able to get the profile information just fine from the sample. I'm adding code to get messages from the inbox. When I do the following:

`var mailResults = await graphClient.Me.MailFolders.Inbox.Messages.Request()`

I get access denied like so:

ServiceException: Code: ErrorAccessDenied
Message: Access is denied. Check credentials and try again.

If it's already authenticated, why am I getting invalid credentials with this?

Thanks!

**Comment by mark-szabo** [comment]
Hey @tgallatin, have you added `Mail.Read` to the scopes? You need to request access to specific resources when getting the token.
https://docs.microsoft.com/en-us/graph/permissions-reference#mail-permissions

**Comment by tgallatin** [comment]
Great. That was the issue. Easy fix. Thanks!
