### ISSUE TITLE
The cached _graphClient instance in GraphSDKHelper is not used

### ISSUE THREAD

**Issue by John-Garland** [microsoftgraph/aspnetcore-connect-sample#4]
The _graphClient field in GraphSDK helper appears to be there in order to cache the reference between executions of the GetAuthenticatedClient method. Except that the private field is only ever referenced from this function, and is generated new for every single function call. Either the call needs to be changed to check it against null and then create the instance if null, or the variable can be moved from a field to a local function variable.

**Comment by jamescro** [comment]
Thanks for spotting this. That field is a vestige of an earlier version of the sample, and we're no longer following that pattern. We'll remove it in the next week or two.

**Comment by mark-szabo** [comment]
Hi @dotnetgator, in theory this should have fixed too with the new MSAL implementation. Please have a look and reopen if you find the issue valid.
