### ISSUE TITLE
ConfidentialClientApplication.AcquireTokenForClientAsync(IEnumerable<string>)' is obsolete

### ISSUE THREAD

**Issue by zulander1** [microsoftgraph/aspnetcore-connect-sample#42]
Error	CS0619	'ConfidentialClientApplication.AcquireTokenForClientAsync(IEnumerable<string>)' is obsolete: 'Use AcquireTokenForClient instead. See https://aka.ms/msal-net-3-breaking-changes'	Kalisto	C:\Users\NS-X\source\repos\LexisMedia\kalisto\Helper\SyncMailBoxHelper.cs	261	Active

This line is obsolete
https://github.com/microsoftgraph/aspnetcore-connect-sample/blob/d65b84f659b31e6600d67ca7e08211639197069d/MicrosoftGraphAspNetCoreConnectSample/Helpers/GraphAuthProvider.cs#L49

**Comment by zulander1** [comment]
Should be                

`var result = await _app.AcquireTokenForClient(_scopes).ExecuteAsync();
`

**Comment by mark-szabo** [comment]
Fixed in pull request #41. Thanks for reporting! 👍
