### ISSUE TITLE
Authentication success, but after redirect to site Getting the error page - Azure app service

### ISSUE THREAD

**Issue by anurajrajagopal** [microsoftgraph/aspnetcore-connect-sample#43]
Hi All,
After authentication, the site is redirecting to error page. May i know what could be the cause. all the settings were made as per your guide.

Error.
An error occurred while processing your request.
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.

Thanks
Anuraj Rajagopal

**Comment by anurajrajagopal** [comment]
Able to fix the issue. the URL pointing to tenantid/v2.0 , now I changed to common/v2.0 and now working fine.
But facing another problem not getting profile photo?

Error:
Code: ErrorAccessDenied
Message: Access to OData is disabled.

Inner error

Thanks,
Anuraj Rajagopal

**Comment by mark-szabo** [comment]
Which version of the graph API are you using? v1.0 or beta? What kind of account are you using to sign in? Personal, or Work or school account?
