### ISSUE TITLE
The profile picture is not loading and getting access denied error. 

### ISSUE THREAD

**Issue by anurajrajagopal** [microsoftgraph/aspnetcore-connect-sample#44]
Hi Team,

Able to read the user profile details. But the profile picture is not loading and getting below 
exception. Have set the readbasic and read properties as well.

Code: ErrorAccessDenied
Message: Access to OData is disabled.

Please help to figure it out.

Thanks,
Anuraj Rajagopal

**Comment by mark-szabo** [comment]
Which version of the graph API are you using? v1.0 or beta? What kind of account are you using to sign in? Personal, or Work or school account?
