### ISSUE TITLE
User not found in token cache

### ISSUE THREAD

**Issue by rajat28negi** [microsoftgraph/aspnetcore-connect-sample#45]
Getting the null in
 var account = await _app.GetAccountAsync(userId);
How i will get the account value  and How to store token in cache?

**Comment by mark-szabo** [comment]
Yes this can happen when you are running the app locally, open the website, log in, then shut down the debugging, restart it (for example after some code changes). So when you restart the app, it clears the server token cache, but your cookie is the same on the frontend. So after restart, the cookie is still authenticated but the user is missing from the token cache.

I hope I could help! 😊

**Comment by colbroth** [comment]
I am having the same issue. Getting null in this call:
var account = await _app.GetAccountAsync(userId);
I issued var accounts = await _app.GetAccountsAsync() and there is one entry with key 
{a unique id, not sure how derived?}.{this value matches claims type identityprovider}
But the example indicates userId is {claims type objectidentifier}.{tenantid}

I am using a different authority than the example 
 _app = ConfidentialClientApplicationBuilder.Create(azureOptions.ClientId)
                .WithClientSecret(azureOptions.ClientSecret)
                .WithAuthority(AzureCloudInstance.AzurePublic, Guid.Parse(azureOptions.TenantId))
                .WithTenantId(azureOptions.TenantId)
                .WithRedirectUri(azureOptions.BaseUrl + azureOptions.CallbackPath)
                .Build();

I have two organizations listed at https://account.activedirectory.windowsazure.com/r#/applications. The second organization contains the active directory group information I need, hence I have to send in the TenantId of the second organization.

WORKAROUND: I am currently using a workaround to solve the issue. In the GraphAuthProvider.cs file, GetUserAccessTokenAsync, I am able to acquire the token by calling
 var result = await _app.AcquireTokenSilent(_scopes, email).ExecuteAsync();
But I would like to know how to determine the userid directly so I can use the original code that gets the account by userId.

Is this sample more recent than the sample at https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph?

**Comment by jmprieur** [comment]
@colbroth @mark-szabo 
could you please try again. We think we have fixed an issue which was related to cache with guest accounts

**Comment by colbroth** [comment]
It works! @jmprieur With the update to use Microsoft.Graph version 1.16.0 and Microsoft.Identity.Client version 4.2.1, the call to GetAccountsAsync(userId) is no longer returning null.

**Comment by colbroth** [comment]
@jmprieur I have the same issue with update

**Comment by anujabhojani** [comment]
@jmprieur  After update, I have the same issue with guest account.

**Comment by mark-szabo** [comment]
Same as #62.
