### ISSUE TITLE
Supported account types issue

### ISSUE THREAD

**Issue by TCrosmanDSI** [microsoftgraph/aspnetcore-connect-sample#46]
Where do i set supported account types?  It's not an option when registering the application in Azure, and I don't see it in the manifest.

I can only get this example to run if i select "Accounts in any organizational directory", but I'd like to only allow internal users.

**Comment by mark-szabo** [comment]
You need to set this when you register the application on the Azure portal:
![image](https://user-images.githubusercontent.com/3098994/87680901-45dadf00-c77e-11ea-8f95-f45706277c90.png)

As well when you create the `ConfidentialClientApplication`. 
`.WithAuthority()'`s second parameter has 4 options:

- **`AzureAdMyOrg`** Users with a Microsoft work or school account in my organization’s Azure AD tenant (i.e. single tenant). Maps to `https://[instance]/[tenantId]`
- **`AzureAdAndPersonalMicrosoftAccount`** Users with a personal Microsoft account, or a work or school account in any organization’s Azure AD tenant. Maps to `https://[instance]/common/`
- **`AzureAdMultipleOrgs`** Users with a Microsoft work or school account in any organization’s Azure AD tenant (i.e. multi-tenant). Maps to `https://[instance]/organizations/`
- **`PersonalMicrosoftAccount`** Users with a personal Microsoft account. Maps to `https://[instance]/consumers/`
