### ISSUE TITLE
After signin in to AAD - Exception: Correlation failed. 

### ISSUE THREAD

**Issue by maszeq** [microsoftgraph/aspnetcore-connect-sample#59]
Hi,
I've followed the sample, when I run the IIS on localhost and click Sign In then go through the authentication process I end up with:

An unhandled exception occurred while processing the request.

Exception: Correlation failed.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by mark-szabo** [comment]
Thanks @maszeq for the report! I'll migrate to .NET Core 3.1 and refactor this sample in about two weeks time and will try to repro this issue as well. 🙂

**Comment by mark-szabo** [comment]
Hia @maszeq the migration has been completed, the authentication libraries upgraded. I wasn't able to repro the aforementioned issue. Can you please re-check and in case the problem still persist, provide mw with more information (what kind of account did you use to log in, etc)?
