### ISSUE TITLE
The reply address does not match the reply addresses configured for the application

### ISSUE THREAD

**Issue by aredfox** [microsoftgraph/aspnetcore-connect-sample#6]
I have configured an application via the portal (converged). I was running under a differen port though, so when settup up the URLS in the app registrations I changed them to match my port number...

Now I'm receiving this error after the flow is trying to connect back to my application. How can I debug this, or how do I know what is happening?

```
Additional technical information:
--
Correlation ID: 145d8f37-7229-4dce-8ace-c777e4aeef94
Timestamp: 2017-11-02 08:41:21Z
AADSTS50011: The reply address 'http://localhost:60761/signin-oidc' does not match the reply addresses configured for the application: '8b640f9d-e7d8-4c41-8a40-15069f5712ee'. More details: not specified
```
![azureadconvergederror](https://user-images.githubusercontent.com/1333704/32316992-9779a8c2-bfb2-11e7-8470-e7a3e6ac82af.PNG)

**Comment by mark-szabo** [comment]
Hi @aredfox,
when you create your app on https://apps.dev.microsoft.com, you have to update the reply URL, if you change it in the code. Just modify the port in the Redirect URLs field, or add a new line and enter the full URL.
![image](https://user-images.githubusercontent.com/3098994/32318710-54760fe2-bfb8-11e7-8125-fa87e171896c.png)

Hope it helps! :) Feel free to leave a comment if you have any questions!

**Comment by mark-szabo** [comment]
Ohh, I see, I've misunderstand your question! :)
So basically the URL on the portal needs to match the URL in [appsettings.json](https://github.com/microsoftgraph/aspnetcore-connect-sample/blob/master/MicrosoftGraphAspNetCoreConnectSample/appsettings.json#L5). Please update the `BaseUrl` field and it should work!

**Comment by mark-szabo** [comment]
Feel free to reopen if you were not able to solve the problem or have more questions! :)
