### ISSUE TITLE
Retrieve user groups in Startup.cs

### ISSUE THREAD

**Issue by sameer-kumar** [microsoftgraph/aspnetcore-connect-sample#64]
**Bug description**

**Repro steps**
I'm trying to modify the your sample to pull user group membership in Startup.cs class file so that I can add user groups as claims. But I could not make it to work. Is it something not possible or I'm doing something wrong? Can you please help me with sample code or pointers? 
Thank you!

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jasonjoh** [comment]
Closing issue as we are archiving this repository.
