### ISSUE TITLE
Error when running application (single-tenant vs multi-tenant) 

### ISSUE THREAD

**Issue by hgjura** [microsoftgraph/aspnetcore-connect-sample#65]
I run this app after filling in the details as instructed. I get this error after trying to Login

OpenIdConnectProtocolException: Message contains error: 'invalid_request', error_description: 'AADSTS50194: Application '{id}'({name} is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

I did not see any instructions for this to be a multi-tenant app.

**Comment by JerryLan01** [comment]
Has there been a resolution for this issue?  I am having the same problem.  My app is set to single-tenant. There is no "/common" endpoint in my code.

**Comment by wayneelaf** [comment]
I am getting the same error.  Has there been any resolution? Any response would be appreciated.  Thanks

**Comment by jasonjoh** [comment]
Closing issue as we are archiving this repository.

To answer your question: In single-tenant apps, MSAL must be given the tenant ID. You should be able to set the `TenantId` property in this section of appsettings.json:

https://github.com/microsoftgraph/aspnetcore-connect-sample/blob/4d237da78fc59d83ed358a57ab70694f810b98a1/MicrosoftGraphAspNetCoreConnectSample/appsettings.json#L2-L10
