### ISSUE TITLE
Issues porting the sample logic to a fresh (razor) application

### ISSUE THREAD

**Issue by Sharor** [microsoftgraph/aspnetcore-connect-sample#9]
Hello, 

Really cool sample first of all - it works quite well when I just clone and run it, and since I was looking to help automate some of my emailing it's exactly what I was looking for 🙂 

Your [contributing section](https://github.com/microsoftgraph/aspnetcore-connect-sample/blob/master/CONTRIBUTING.md#how-to-use-markdown-to-format-your-topic) article link leads nowhere by the way, so sorry if this issue is not in the desired format.

I am having an issue with the login process, which is odd. I did the following: 

I have a completely fresh .NET core application, created by selecting "Web" (not MVC, Razor Pages I think), including authentication. 

I then initially added a Microsoft account, which worked fine for authentication and logs me in. 

Then I looked at this sample, which runs great locally after creating an application id / secret in the portal, and it correctly links my full name from my account. 

Wanting to port the sample logic to my app, I changed startup (see below, included outcommented microsoft account logic): 

```
public class Startup
{
  public Startup(IConfiguration configuration)
  {
    Configuration = configuration;
  }

  public IConfiguration Configuration { get; }
  public const string ObjectIdentifierType = "http://schemas.microsoft.com/identity/claims/objectidentifier";
  public const string TenantIdType = "http://schemas.microsoft.com/identity/claims/tenantid";


  // This method gets called by the runtime. Use this method to add services to the container.
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddDbContext<ApplicationDbContext>(options =>
      options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

    services.AddIdentity<ApplicationUser, IdentityRole>()
      .AddEntityFrameworkStores<ApplicationDbContext>()
      .AddDefaultTokenProviders();

    //services.AddAuthentication().AddMicrosoftAccount(options =>
    //{
    //	options.ClientId = Configuration["Authentication:Microsoft:ApplicationId"];
    //	options.ClientSecret = Configuration["Authentication:Microsoft:Password"];
    //});

    services.AddAuthentication(sharedOptions =>
    {
      sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
      sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
      sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    })
    .AddAzureAd(options => Configuration.Bind("AzureAd", options))
    .AddCookie();
    // This sample uses an in-memory cache for tokens and subscriptions. Production apps will typically use some method of persistent storage.
    services.AddMemoryCache();
    services.AddSession();

    // Add application services.
    //services.AddSingleton<IConfiguration>(Configuration);
    services.AddSingleton<IGraphAuthProvider, GraphAuthProvider>();
    services.AddTransient<IGraphSdkHelper, GraphSdkHelper>();

    services.AddMvc()
      .AddRazorPagesOptions(options =>
      {
        options.Conventions.AuthorizeFolder("/Account/Manage");
        options.Conventions.AuthorizePage("/Account/Logout");
      });

    // Register no-op EmailSender used by account confirmation and password reset during development
    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=532713
    services.AddSingleton<IEmailSender, EmailSender>();
  }

  // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
  public void Configure(IApplicationBuilder app, IHostingEnvironment env)
  {
    if (env.IsDevelopment())
    {
      app.UseDeveloperExceptionPage();
      app.UseBrowserLink();
      app.UseDatabaseErrorPage();
    }
    else
    {
      app.UseExceptionHandler("/Error");
    }

    app.UseStaticFiles();
    app.UseSession();
    app.UseAuthentication();
    app.UseMvc(routes =>
    {
      routes.MapRoute(
        name: "default",
        template: "{controller}/{action=Index}/{id?}");
    });
  }
}
```

I copied the AzureAD settings from my working sample, and changed the port to match the app, and copied the "helper" folder with all cs files, and the extensions files into the extensions folder, added the nuget packages required and run the application. 

What happens is I go through the whole authentication flow, all the way up to registering external provider and then the application throws me back to the index page, without having authenticated. 

Pointers to what I'm doing wrong, and how I can port your logic to an existing application? 🙂

**Comment by Sharor** [comment]
Update: 

I recreated the behaviour by slowly adding bits and pieces to the dotnet core sample application (this repository). 

doing: 
```
services.AddIdentity<ApplicationUser, IdentityRole>()
  .AddEntityFrameworkStores<ApplicationDbContext>()
  .AddDefaultTokenProviders();
```

Has the effect I saw, where you "login" but nothing happens. I tried outcommenting the lines dealing with EntityFramework in my Razor app, but that did not remove the problem, so there might be more to it. 😕

**Comment by Sharor** [comment]
So I spent a couple of days reading up on MSAL and trying different solutions. I found out the problem comes with some under the hood middleware I cannot quite see my way out of. 

So what happens is as follows: 
- adding identity like so: 
```
services.AddIdentity<ApplicationUser, IdentityRole>()
  .AddEntityFrameworkStores<ApplicationDbContext>()
  .AddDefaultTokenProviders();
```
causes there to be a mismatch between the openidconnect authentication and identity somehow, so even after logging in the ```User.Identity.IsAuthenticated``` has the value false. 

All the other solutions I found (https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp/tree/core2.0 was the best) all uses Azure Tenants, which I could not make work from the example. However I later found out my windows system clock running an hour early caused invalidation of tokens, so it might have caused it. 

I've been unable to link Entity identity and OpenIdConnect so far, but I suspect there is a way to somehow make identity aware of AzureAd, or vice versa? I just haven't been able to google my way there. 

@mark-szabo  do you happen to know of some flag that allows AddIdentity to be aware of the OpenIdConnect middleware, as I suspect that will solve the problem? 🙂 :christmas_tree:

**Comment by Sharor** [comment]
Had a small breakthrough, by dumping my entity database - oidc apparantly does not do very well if there is already a user defined in it, which shares email with the login. Still have not been able to port it to razor, however - it seems like adding the razor pages bit to ```services.AddMvc()...<razorpages config> ``` might be what's causing the problem. 😕

**Comment by Sharor** [comment]
No, it is not caused by adding razor pages. 

Creating a brand new project in Visual Studio, selecting authentication with individual accounts, and then migrating this example still has the same "log in but not logged in" issue. Which is interesting. I debugged it all the way past the ExternalLoginCallback method, which correctly authenticates, registers the user in the database and then.. crash. 

However when reauthenticating, the signing in is a success and should have the user authenticated. But it does not.

**Comment by mark-szabo** [comment]
Hi @Sharor, I'm so sorry for the delay. The thing is, that I haven't used this sample with EntityFramework yet. But it is in plan on one of my apps, so in the coming weeks, I'll have a look on it. If it's ok for you, I'll report my findings here.
Thanks for reporting it and have a Merry Christmas! 🐱‍💻🎄

**Comment by Sharor** [comment]
@mark-szabo it's all good, I can relate to how busy it is up to christmas 😉

I really appreciate your work here though, and I've been using your example without entity to get some of my logic running. It's been a great help.  I have successfully integrated with my work calendar, and it's already making my life easier 😄 I was just really hoping to expand functionality to include the entity things because that will also allow me to use my google calendar and do the same thing together with outlook all at once 😉 

I hope you have a wonderful christmas! 🎄 🎁

**Comment by mark-szabo** [comment]
@Sharor so as promised I was tinkering with the app that uses EF, aspnetcore2.0, MSAL and Graph. 
I was able to get it working, but instead of 
```
services.AddIdentity<ApplicationUser, IdentityRole>()
  .AddEntityFrameworkStores<ApplicationDbContext>()
  .AddDefaultTokenProviders();
```
I've used 
```
services.AddDbContextPool<ApplicationDbContext>(options => 
  options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

For me `User.Identity.IsAuthenticated` always shows the correct authentication state.

Let me know what you think! 😊😉

**Comment by Sharor** [comment]
@mark-szabo - awesome dude 😄 I'll have a look when I have time next! I'll do my best to make some time this week 😉

**Comment by mark-szabo** [comment]
hi @Sharor, did you have time to check out the above mentioned thing?
Thanks! :)

**Comment by Sharor** [comment]
@mark-szabo sorry I totally forgot to answer, moved house and it's just been a lot to juggle in my head - yes I did test it, and it works great! 

I'll be closing the issue, thank you so much for your help - really good work on all of it 😄

**Comment by mark-szabo** [comment]
@Sharor awesome! Glad that we were able to help! :) 
Thank you for using Microsoft Graph, and feel free to contact us if you have any problem!
